### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by boombaklot** [vavkamil/Bitcoin-Sweeper#1]
Output not decrypted. Errors in almost every line, uncracked ,ecdsa seems to not work, cannot link blockchain wallet neither

**Comment by boombaklot** [comment]
Here is the errors I keep getting

root@localhost:/# cd
root@localhost:~# cd Bitcoin-Sweeper
root@localhost:~/Bitcoin-Sweeper# perl output.txt
Bareword found where operator expected at output.txt line 1, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 2, near "appointive
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 2, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 3, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 3, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Bareword found where operator expected at output.txt line 3, near "5JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf"
        (Missing operator before JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf?)
Number found where operator expected at output.txt line 4, near "JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 4, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 6, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 6, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 7, near "exacerbate
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 7, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 8, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 8, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Bareword found where operator expected at output.txt line 8, near "5JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL"
        (Missing operator before JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL?)
Number found where operator expected at output.txt line 9, near "JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 9, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 11, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 11, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 12, near "accentuating
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 12, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 13, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 13, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Bareword found where operator expected at output.txt line 13, near "5JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL"
        (Missing operator before JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL?)
Number found where operator expected at output.txt line 14, near "JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 14, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 16, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 16, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 17, near "forgiveness
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 17, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 18, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 18, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Bareword found where operator expected at output.txt line 18, near "5JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA"
        (Missing operator before JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA?)
Number found where operator expected at output.txt line 19, near "JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 19, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 21, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 21, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 22, near "appointive
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 22, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 23, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 23, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Bareword found where operator expected at output.txt line 23, near "5JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf"
        (Missing operator before JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf?)
Number found where operator expected at output.txt line 24, near "JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 24, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 26, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 26, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 27, near "exacerbate
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 27, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 28, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 28, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Bareword found where operator expected at output.txt line 28, near "5JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL"
        (Missing operator before JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL?)
Number found where operator expected at output.txt line 29, near "JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 29, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 31, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 31, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 32, near "accentuating
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 32, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 33, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 33, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Bareword found where operator expected at output.txt line 33, near "5JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL"
        (Missing operator before JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL?)
Number found where operator expected at output.txt line 34, near "JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 34, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 36, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 36, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 37, near "forgiveness
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 37, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 38, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 38, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Bareword found where operator expected at output.txt line 38, near "5JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA"
        (Missing operator before JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA?)
Number found where operator expected at output.txt line 39, near "JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 39, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 41, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 41, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 42, near "appointive
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 42, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 43, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 43, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Bareword found where operator expected at output.txt line 43, near "5JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf"
        (Missing operator before JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf?)
Number found where operator expected at output.txt line 44, near "JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 44, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 46, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 46, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 47, near "exacerbate
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 47, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 48, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 48, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Bareword found where operator expected at output.txt line 48, near "5JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL"
        (Missing operator before JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL?)
Number found where operator expected at output.txt line 49, near "JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 49, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 51, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 51, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 52, near "accentuating
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 52, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 53, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 53, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Bareword found where operator expected at output.txt line 53, near "5JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL"
        (Missing operator before JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL?)
Number found where operator expected at output.txt line 54, near "JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 54, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 56, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 56, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 57, near "forgiveness
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 57, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 58, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 58, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Bareword found where operator expected at output.txt line 58, near "5JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA"
        (Missing operator before JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA?)
Number found where operator expected at output.txt line 59, near "JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 59, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 61, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 61, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 62, near "appointive
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 62, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 63, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 63, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Bareword found where operator expected at output.txt line 63, near "5JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf"
        (Missing operator before JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf?)
Number found where operator expected at output.txt line 64, near "JhijED9PdJHxBhAqFW3kWaJRkvckFsLY7jou4BmqnEmzf5WMHf
18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 64, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
        (Missing operator before X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6?)
Number found where operator expected at output.txt line 66, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 66, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 67, near "exacerbate
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 67, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 68, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 68, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Bareword found where operator expected at output.txt line 68, near "5JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL"
        (Missing operator before JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL?)
Number found where operator expected at output.txt line 69, near "JGhAhbVZwegbTVZYqxTLFCuXRXxDJMFfwfWcisMhVRtQfXxFyL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 69, near "1AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A"
        (Missing operator before AW3C1pC7r8LgWQbHFfEW8XjB5e8tfYc1A?)
Number found where operator expected at output.txt line 71, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 71, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 72, near "accentuating
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 72, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 73, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 73, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Bareword found where operator expected at output.txt line 73, near "5JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL"
        (Missing operator before JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL?)
Number found where operator expected at output.txt line 74, near "JxeYPjzzfG6sGoRXEQunWPo7Skv8Mt17ZvcfHHDXJzVLn7sDWL
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 74, near "1DYmfSvaXdaFMjA7qsuQMgs82tKuderViS"
        (Missing operator before DYmfSvaXdaFMjA7qsuQMgs82tKuderViS?)
Number found where operator expected at output.txt line 76, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 76, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 77, near "forgiveness
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 77, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Number found where operator expected at output.txt line 78, near "1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 78, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
Bareword found where operator expected at output.txt line 78, near "5JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA"
        (Missing operator before JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA?)
Number found where operator expected at output.txt line 79, near "JTBdKSeLsyPDSMfXvYE9FdAsjXV7k6GBrhxXLEdUtj477P8qPA
1"
        (Missing semicolon on previous line?)
Bareword found where operator expected at output.txt line 79, near "1LBG3NrauAGidWWNAUVX1AkkViFwyuAytU"
        (Missing operator before LBG3NrauAGidWWNAUVX1AkkViFwyuAytU?)
syntax error at output.txt line 1, near "18X6yC1p1hXvXjuwZfjT52Z1am9LNuAAC6"
Execution of output.txt aborted due to compilation errors.
root@localhost:~/Bitcoin-Sweeper#

**Comment by boombaklot** [comment]
Any help?

**Comment by vavkamil** [comment]
perl btc_sweeper.pl -w passphrases.txt -t 1 -o new_output.txt


2015-01-17 15:09 GMT+01:00 boombaklot <notifications@github.com>:
